### ISSUE TITLE
Ignorer chinook.db

### ISSUE THREAD

**Issue by tanguy-perennou** [alexiaauddino/chinook-alexia-auddino#1]
Par défaut, tu ignores `db.sqlite3`. Il faut adapter pour ignorer `chinook.db`.

**Comment by tanguy-perennou** [comment]
Vu dans ton code, `.gitignore` modifié. Pour les prochaines *issues*, fais une réponse sous forme de commentaire, et je pourrai fermer l'_issue_.

**Comment by alexiaauddino** [comment]
D'accord désolée, donc oui j'ai corrigé le fichier .gitignore

**Comment by tanguy-perennou** [comment]
👍
